export {default as Dashboard } from './Dashboard/Dashboard'
export {default as Team } from './Team/Team'
export {default as Contacts} from './Contacts/Contacts'
export {default as Invoice } from './invoice/Invoice'
export {default as Form } from './Form/Form'
export {default as Calender} from './Calender/Calender'
export {default as Faq } from './Faq/Faq'
export {default as Chart } from './Chart/Chart'
export {default as Pie } from './Pie/Pie'
export {default as Line } from './Line/Line'
export {default as Geography } from './Geography/Geography'